//! Error layer.
//!
//! Every fallible operation in `htmltoapk` returns [`Result<T>`]. Errors carry a
//! short headline (via [`std::fmt::Display`]) plus an optional actionable hint
//! that the UI layer renders below the headline. Core logic never prints:
//! it only returns errors, which keeps CLI and TUI rendering identical.

use std::fmt;
use std::io;
use std::path::PathBuf;

/// Convenient crate-wide result alias.
pub type Result<T> = std::result::Result<T, Error>;

/// All failures produced by the core layer.
#[derive(Debug)]
pub enum Error {
    /// An external executable (node, npm, npx, java, ...) is not in `PATH`.
    MissingTool { tool: String, hint: String },
    /// The Android SDK is missing or incomplete.
    AndroidSdk { reason: String, hint: String },
    /// The requested input path does not exist.
    InputNotFound { path: PathBuf },
    /// The input exists but cannot be used as a web app source.
    InvalidInput { path: PathBuf, reason: String },
    /// The configuration file (or a value in it) is invalid.
    InvalidConfig {
        path: Option<PathBuf>,
        reason: String,
    },
    /// A build stage exited with a non-zero status.
    BuildFailed {
        stage: String,
        code: Option<i32>,
        log: Option<PathBuf>,
        tail: String,
    },
    /// Filesystem or process I/O failure with human context.
    Io { context: String, source: io::Error },
    /// The user aborted an interactive prompt.
    Cancelled,
    /// Anything else, with an optional hint.
    Other {
        message: String,
        hint: Option<String>,
    },
}

impl Error {
    /// Wrap an [`io::Error`] with human-readable context.
    pub fn io(context: impl Into<String>, source: io::Error) -> Self {
        Error::Io {
            context: context.into(),
            source,
        }
    }

    /// A plain error message.
    pub fn other(message: impl Into<String>) -> Self {
        Error::Other {
            message: message.into(),
            hint: None,
        }
    }

    /// A plain error message with a hint for the user.
    pub fn with_hint(message: impl Into<String>, hint: impl Into<String>) -> Self {
        Error::Other {
            message: message.into(),
            hint: Some(hint.into()),
        }
    }

    /// Invalid configuration value (no file attached).
    pub fn config(reason: impl Into<String>) -> Self {
        Error::InvalidConfig {
            path: None,
            reason: reason.into(),
        }
    }

    /// Build a `MissingTool` error with a tool-specific installation hint.
    pub fn missing_tool(tool: &str) -> Self {
        let hint = match tool {
            "node" => "Install Node.js 18+ (LTS is recommended).\n  \
                       Debian/Ubuntu: sudo apt install nodejs npm\n  \
                       Fedora:        sudo dnf install nodejs\n  \
                       Arch:          sudo pacman -S nodejs npm\n  \
                       Or use a version manager: https://github.com/nvm-sh/nvm"
                .to_string(),
            "npm" => "npm ships with Node.js. Install Node.js 18+ or reinstall it so that `npm` lands in PATH.\n  \
                      Check with: node --version && npm --version"
                .to_string(),
            "npx" => "npx ships with npm 7+. Upgrade npm with: npm install -g npm@latest".to_string(),
            "java" | "javac" => "Install a JDK 17 (required by the Android Gradle Plugin).\n  \
                                 Debian/Ubuntu: sudo apt install openjdk-17-jdk\n  \
                                 Fedora:        sudo dnf install java-17-openjdk-devel\n  \
                                 Arch:          sudo pacman -S jdk17-openjdk\n  \
                                 Then export JAVA_HOME to the JDK root."
                .to_string(),
            "gradle" => "No system Gradle is required: htmltoapk uses the Gradle wrapper generated by Capacitor."
                .to_string(),
            other => format!("Install `{other}` and make sure it is reachable from PATH."),
        };
        Error::MissingTool {
            tool: tool.to_string(),
            hint,
        }
    }

    /// An actionable hint shown under the headline by the UI layer.
    pub fn hint(&self) -> Option<String> {
        match self {
            Error::MissingTool { hint, .. } => Some(hint.clone()),
            Error::AndroidSdk { hint, .. } => Some(hint.clone()),
            Error::InputNotFound { .. } => Some(
                "Pass a path to a single .html file or to a directory containing index.html."
                    .to_string(),
            ),
            Error::InvalidInput { .. } => Some(
                "Supported inputs: a single-file HTML document, or a web directory with an index.html entry point."
                    .to_string(),
            ),
            Error::InvalidConfig { path, .. } => Some(match path {
                Some(p) => format!(
                    "Fix the file at {} or reset it with: htmltoapk config reset",
                    p.display()
                ),
                None => "Inspect current values with: htmltoapk config".to_string(),
            }),
            Error::BuildFailed { log, tail, .. } => {
                let mut hint = String::new();
                if !tail.trim().is_empty() {
                    hint.push_str("Last lines of the build log:\n");
                    for line in tail.lines() {
                        hint.push_str("  | ");
                        hint.push_str(line);
                        hint.push('\n');
                    }
                }
                if let Some(path) = log {
                    hint.push_str(&format!("Full log: {}", path.display()));
                } else {
                    hint.push_str("Re-run with `htmltoapk doctor` to verify the toolchain.");
                }
                Some(hint)
            }
            Error::Io { .. } => None,
            Error::Cancelled => None,
            Error::Other { hint, .. } => hint.clone(),
        }
    }

    /// Process exit code, so scripts can branch on the failure class.
    pub fn exit_code(&self) -> i32 {
        match self {
            Error::MissingTool { .. } => 3,
            Error::AndroidSdk { .. } => 4,
            Error::InputNotFound { .. } => 5,
            Error::InvalidInput { .. } => 5,
            Error::InvalidConfig { .. } => 6,
            Error::BuildFailed { .. } => 7,
            Error::Io { .. } => 8,
            Error::Cancelled => 130,
            Error::Other { .. } => 1,
        }
    }
}

impl fmt::Display for Error {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Error::MissingTool { tool, .. } => {
                write!(f, "required tool `{tool}` was not found in PATH")
            }
            Error::AndroidSdk { reason, .. } => write!(f, "Android SDK is not usable: {reason}"),
            Error::InputNotFound { path } => {
                write!(f, "input path does not exist: {}", path.display())
            }
            Error::InvalidInput { path, reason } => {
                write!(f, "invalid input `{}`: {reason}", path.display())
            }
            Error::InvalidConfig { path, reason } => match path {
                Some(p) => write!(f, "invalid configuration ({}): {reason}", p.display()),
                None => write!(f, "invalid configuration: {reason}"),
            },
            Error::BuildFailed { stage, code, .. } => {
                write!(f, "build failed during stage `{stage}`")?;
                if let Some(code) = code {
                    write!(f, " (exit code {code})")?;
                }
                Ok(())
            }
            Error::Io { context, source } => write!(f, "{context}: {source}"),
            Error::Cancelled => write!(f, "cancelled"),
            Error::Other { message, .. } => write!(f, "{message}"),
        }
    }
}

impl std::error::Error for Error {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            Error::Io { source, .. } => Some(source),
            _ => None,
        }
    }
}

/// Attach human context to `std::io` results: `fs::read(p).ctx("...")?`.
pub trait IoContext<T> {
    fn ctx(self, context: impl Into<String>) -> Result<T>;
}

impl<T> IoContext<T> for std::result::Result<T, io::Error> {
    fn ctx(self, context: impl Into<String>) -> Result<T> {
        self.map_err(|source| Error::io(context, source))
    }
}
